[package]
name = "fn-fs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
fn-core = { path = "../fn-core" }
notify = "6"
once_cell = "1"
thiserror.workspace = true

[dev-dependencies]
tempfile = "3"
